runtime: python
env: flex
runtime_config:
  python_version: 3.9

entrypoint: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5

requirements_path: requirements-deploy.txt
